name: gotrip
description: FYP Smart Landmark Recognition App
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1  # 添加这一行
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  http: ^1.2.0
  image_picker: ^0.8.7+4
  lottie: ^3.1.2
  fl_chart: ^0.70.0


dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/cn.json
