// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiiaE4yMNdAJAkWBBRbI47vJjPscB9CFA',
    appId: '1:531377587322:web:29dd1085db8f5366dae7c3',
    messagingSenderId: '531377587322',
    projectId: 'gotrip-application',
    authDomain: 'gotrip-application.firebaseapp.com',
    storageBucket: 'gotrip-application.firebasestorage.app',
    measurementId: 'G-V80BVSYCC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIFxUh6gTjzLY4hI9CGbwtY_3c52Ov1XQ',
    appId: '1:531377587322:android:1092f484acc04c4adae7c3',
    messagingSenderId: '531377587322',
    projectId: 'gotrip-application',
    storageBucket: 'gotrip-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmOrJvehGP37tzoLwrKVQOoJRRi8soXl4',
    appId: '1:531377587322:ios:5497c8fd01dd916edae7c3',
    messagingSenderId: '531377587322',
    projectId: 'gotrip-application',
    storageBucket: 'gotrip-application.firebasestorage.app',
    iosBundleId: 'com.example.gotrip',
  );
}
